name: Build

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout

            - name: Configure node
              uses: actions/setup-node
              with:
                  node-version: 22.0.0

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: Build project
              run: npm run build

            - name: Greeting
              run: echo "Brawo! Znakomita robota!"
