name: Build

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.0.0

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: dev project
              run: npm run dev

            - name: Greeting
              run: echo "Brawo! Znakomita robota!"
